name: train
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - kernda
  - pip
  - gdal 
  - numpy 
  - pandas 
  - importlib-metadata 
  - scipy 
  - netcdf4 
  - boto3 
  - lxml 
  - pyproj
  - pip:
    - asf_hyp3
    - hyp3-sdk~=1.0