name: train
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.8
  - jupyter
  - kernda
  - ipykernel=5.5.5
  - gdal=3.1.3
  - numpy
  - pandas
  - pip
  - importlib-metadata
  - scipy
  - netcdf4
  - boto3
  - lxml
  - pyproj
  - matplotlib
  - asf_search
  - ipympl
  - opensarlab_lib
  - hyp3_sdk
  - pip:
    - hyp3lib==1.4.1
    - url-widget
