[workspace]
authors = ["segallagher <segallagher@alaska.edu>"]
channels = ["conda-forge", "pyrocko"]
name = "earthscope_insar"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]

[dependencies]
python = ">=3.10,<3.12"
setuptools = "<60"
wheel = "*"

aria-tools = "*"
asf_search = "*"
autorift = "*"
boto3 = "*"
hyp3_sdk = "*"
ipykernel = "*"
ipympl = "*"
isce2 = "*"
libgdal-hdf5 = "*"
libgdal-netcdf = "*"
mintpy = ">=1.6.4"
netcdf4 = "*"
pip = "*"
pv = "*"
pyrocko = "*"
sardem = "*"
rioxarray = "*"
rasterio = "*"
sentineleof = "*"
numpy = ">=1.24.0"
compass = "*"
isce3 = "*"
snaphu = "*"
burst2safe = "*"
whirlwind-insar = ">=0.8.0"
dolphin = "*"

[pypi-dependencies]
url-widget = "*"
okada-wrapper = "==18.12.7.3"
kite = "*"
burst-db = { git = "https://github.com/opera-adt/burst_db.git" }

[pypi-options]
no-build-isolation = ["okada-wrapper"]
